site_name: Projecte Alex 
nav:
  - Home: index.md
  - Sprint2: sprint2.md
  - Sprint3: sprint3.md
  - Sprint4: sprint4.md
  - Sprint5: sprint5.md
  - Sprint6: sprint6.md
  - CCC: ccc.md
  
theme: readthedocs

  
  
  
